version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  builder: "dirhtml"

python:
  install:
    - path: .
    - requirements: dev-requirements.txt